package Entity;

public enum PerformedAction {
    MARK_AS_FALSE,
    RESTRICT_POSTING,
    RESTRICT_COMMENTING,
    SEND_WARNING,
    REMOVE_POST,
    BAN_USER,
    REMOVE_COMMENT,
    CHANGE_ENVIRONMENT_CONFIGURATIONS,
    ADD_NEW_ADMINS,
    REMOVE_EXISTING_ADMINS
}
