package Entity;

public enum ReportReason {
    STOLEN_IDENTITY,
    HACKED_ACCOUNT,
    NOT_BEING_A_REAL_PERSON,
    BEING_FALSE,
    HARASSMENT,
    INAPPROPRIATE_LANGUAGE,
    HATEFUL_SPEECH,
    THREATS_OR_VIOLENCE,
    SELF_HARM,
    SEXUAL_CONTENT,
    INFRINGEMENT,
    SCAM,
    SPAM,
    MISINFORMATION,
    FAKE_ACCOUNT,
    OTHER
}